import type { SafetyLevel, SafetyResult } from './types.js';

export const BLOCKED_PATTERNS: RegExp[] = [
  /^rm\s+-rf\s+\//m,
  /^rm\s+--no-preserve-root\s+/m,
  /^mkfs\./m,
  /^dd\s+if=\/dev\/zero/m,
  /^dd\s+if=\/dev\/urandom/m,
  /:\(\)\{\s*\|:\s*\&\};/m,
  /^chmod\s+-R\s+000\s+\//m,
  /^chown\s+-R\s+/m,
  /^>\/dev\/sda/m,
  /^halt\b/m,
  /^poweroff\b/m,
  /^reboot\b/m,
  /^shutdown\b/m,
  /^init\s+0/m,
  /^init\s+6/m,
  /^systemctl\s+(halt|poweroff|reboot)/m,
  /^pvcreate\b/m,
  /^vgcreate\b/m,
  /^lvcreate\b/m,
  /^pvremove\b/m,
  /^ifconfig\s+\w+\s+down/m,
  /^ip\s+link\s+set\s+\w+\s+down/m,
  /^route\s+del\s+default/m,
  /^iptables\s+-F/m,
  /^ufw\s+disable/m,
  /^sysctl\s+-w/m,
  /^modprobe\s+-r/m,
  /^insmod\b/m,
  /^rmmod\b/m,
  /^dpkg\s+--purge\s+/m,
  /^rpm\s+-e\s+/m,
  /^apt-get\s+(remove|purge)\s+/m,
  /^yum\s+(remove|erase)\s+/m,
  /^pacman\s+-R\s+/m,
  /^grub-install\b/m,
  /^grub-mkconfig\b/m,
  /^update-grub\b/m,
  /^dd\s+if=.*\s+of=\/dev\/sda/m,
  /^gparted\b/m,
  /^fdisk\s+\/dev\/sda/m,
  /^parted\s+\/dev\/sda/m,
  /^mkswap\b/m,
  /^swapon\b/m,
  /^swapoff\b/m,
  /^export\s+DISPLAY/m,
  /^xhost\s+/m,
  /^setxkbmap\b/m,
  /^loadkeys\b/m,
  /^alsamixer\b/m,
  /^amixer\b/m,
  /^pulseaudio\s+-k/m,
  /^killall\s+pulseaudio/m,
  /^systemctl\s+(stop|disable)\s+(NetworkManager|networking)/m,
  /^systemctl\s+(stop|disable)\s+(sshd|ssh|ufw|cron)/m,
  /^update-rc\.d\s+/m,
  /^rc-update\s+/m,
  /^chkconfig\s+off/m,
  /^alternatives\s+--set\s+/m,
  /^update-alternatives\s+--set\s+/m,
  /^setsebool\s+-P\s+/m,
  /^touch\s+\/[^ ]+/m,
  /^rm\s+\/[^ ]+/m,
  /^mv\s+\/[^ ]+\s+\/[^ ]+/m,
  /^passwd\b/m,
  /^useradd\b/m,
  /^userdel\b/m,
  /^groupadd\b/m,
  /^groupdel\b/m,
  /^usermod\b/m,
  /^gpasswd\b/m,
  /^visudo\b/m,
  /^su\s+-/m,
  /^sudo\s+-i/m,
  /^sudo\s+\/bin\/bash/m,
  /^sudo\s+\/bin\/sh/m,
  /^crontab\b/m,
  /^at\b/m,
  /^batch\b/m,
  /^anacron\b/m,
  /^logrotate\s+-f/m,
  /^journalctl\s+--vacuum/m,
  /^syslogd\b/m,
  /^klogd\b/m,
  /^rsyslogd\b/m,
  /^nginx\s+-s\s+stop/m,
  /^apachectl\s+(stop|restart)/m,
  /^systemctl\s+(stop|restart)\s+nginx/m,
  /^systemctl\s+(stop|restart)\s+(apache2|httpd)/m,
  /^certbot\b/m,
  /^openssl\s+req/m,
  /^openssl\s+x509/m,
  /^ssh-keygen\b/m,
  /^gpg\s+--gen-key/m,
  /^gpg\s+--import/m,
  /^gpg\s+--export/m,
  /^gpg\s+--delete/m,
  /^gpg\s+--sign/m,
  /^gpg\s+--encrypt/m,
  /^gpg\s+--decrypt/m,
  /^git\s+config\s+--global/m,
  /^git\s+remote\s+add/m,
  /^git\s+remote\s+set-url/m,
  /^docker\s+(login|logout)/m,
  /^docker\s+push/m,
  /^docker\s+tag/m,
  /^docker\s+image\s+tag/m,
  /^docker\s+system\s+prune/m,
  /^docker\s+container\s+prune/m,
  /^docker\s+image\s+prune/m,
  /^docker\s+volume\s+prune/m,
  /^docker\s+network\s+prune/m,
  /^pip\s+install\s+/m,
  /^pip3\s+install\s+/m,
  /^npm\s+install\s+-g/m,
  /^npm\s+publish/m,
  /^npm\s+unpublish/m,
  /^npm\s+deprecate/m,
  /^npm\s+owner/m,
  /^npx\s+-g\s+/m,
  /^yarn\s+global\s+add/m,
  /^yarn\s+publish/m,
  /^cargo\s+publish/m,
  /^cargo\s+install\s+/m,
  /^gem\s+install\s+/m,
  /^gem\s+push/m,
  /^bundle\s+install\s+/m,
  /^bundle\s+exec\s+/m,
  /^composer\s+global\s+require/m,
  /^dotnet\s+tool\s+install/m,
  /^dotnet\s+pack\s+/m,
  /^dotnet\s+nupush/m,
  /^terraform\s+(apply|destroy)/m,
  /^pulumi\s+up/m,
  /^pulumi\s+destroy/m,
  /^kubectl\s+apply\s+/m,
  /^kubectl\s+delete\s+/m,
  /^kubectl\s+taint/m,
  /^kubectl\s+drain/m,
  /^kubectl\s+cordon/m,
  /^helm\s+install/m,
  /^helm\s+delete/m,
  /^helm\s+uninstall/m,
  /^kubectl\s+create\s+namespace/m,
  /^kubectl\s+create\s+secret/m,
  /^kubectl\s+create\s+configmap/m,
  /^aws\s+iam\s+/m,
  /^aws\s+kms\s+/m,
  /^aws\s+organizations\s+/m,
  /^aws\s+sts\s+/m,
  /^gcloud\s+iam\s+/m,
  /^gcloud\s+kms\s+/m,
  /^az\s+ad\s+/m,
  /^az\s+keyvault\s+/m,
  /^az\s+role\s+/m,
  /^wget\s+.*--post-data/m,
  /^curl\s+.*-d\s+/m,
  /^curl\s+.*--data/m,
  /^curl\s+.*-X\s+(POST|PUT|PATCH|DELETE)/m,
  /^curl\s+.*-F\s+/m,
  /^ssh\s+/m,
  /^scp\b/m,
  /^sftp\b/m,
  /^rsync\s+/m,
  /^telnet\b/m,
  /^nc\s+/m,
  /^ncat\s+/m,
  /^nmap\b/m,
  /^masscan\b/m,
  /^nikto\b/m,
  /^sqlmap\b/m,
  /^hydra\b/m,
  /^john\b/m,
  /^hashcat\b/m,
  /^aircrack-ng\b/m,
  /^aireplay-ng\b/m,
  /^airodump-ng\b/m,
  /^iwconfig\s+.*mode\s+monitor/m,
  /^metasploit\b/m,
  /^msfconsole\b/m,
  /^msfvenom\b/m,
  /^beef-xss\b/m,
  /^ettercap\b/m,
  /^driftnet\b/m,
  /^dsniff\b/m,
  /^tcpdump\s+-i\s+/m,
  /^vi\b/m,
  /^vim\b/m,
  /^nano\b/m,
  /^emacs\b/m,
  /^less\b/m,
  /^more\b/m,
  /^head\b/m,
  /^tail\b/m,
  /^screen\b/m,
  /^tmux\b/m,
  /^byobu\b/m,
  /^clear\b/m,
  /^reset\b/m,
  /^figlet\b/m,
  /^banner\b/m,
  /^fortune\b/m,
  /^cowsay\b/m,
  /^sl\b/m,
  /^yes\b/m,
  /^watch\b/m,
];

export const DANGEROUS_PATTERNS: RegExp[] = [
  /rm\s+-rf/m,
  /rm\s+-r\s+/m,
  /rm\s+-f\s+/m,
  /rm\s+.*--no-preserve-root/m,
  /chmod\s+-R/m,
  /chmod\s+777/m,
  /chmod\s+666/m,
  /chmod\s+000/m,
  /chown\s+/m,
  /mv\s+[\w.\/-]+\s+[\w.\/-]+/m,
  /cp\s+-r\s+/m,
  /cp\s+-f\s+/m,
  /dd\s+if=/m,
  /dd\s+of=/m,
  />\s*\/dev\//m,
  /\/dev\/null/m,
  /\/dev\/zero/m,
  /\/dev\/random/m,
  /\/dev\/urandom/m,
  /SIGKILL/m,
  /SIGTERM/m,
  /kill\s+-9/m,
  /kill\s+-15/m,
  /killall\s+/m,
  /pkill\s+/m,
  /git\s+reset\s+--hard/m,
  /git\s+checkout\s+--/m,
  /git\s+clean\s+-f/m,
  /git\s+rebase\s+/m,
  /git\s+push\s+--force/m,
  /git\s+push\s+-f/m,
  /git\s+reset\s+HEAD~1/m,
  /git\s+commit\s+--amend/m,
  /git\s+update-ref\s+/m,
  /git\s+filter-branch/m,
  /docker\s+rm\s+/m,
  /docker\s+rmi\s+/m,
  /docker\s+stop\s+/m,
  /docker\s+kill\s+/m,
  /docker\s+exec\s+/m,
  /docker\s+run\s+/m,
  /docker\s+start\s+/m,
  /apt-get\s+(install|update|upgrade|dist-upgrade)/m,
  /yum\s+(install|update|upgrade)/m,
  /apt\s+(install|update|upgrade)/m,
  /pacman\s+-S\s+/m,
  /npm\s+(install|update|uninstall)\s+/m,
  /yarn\s+(add|remove|upgrade)\s+/m,
  /pnpm\s+(install|update|uninstall)\s+/m,
  /pip\s+(install|uninstall)\s+/m,
  /pip3\s+(install|uninstall)\s+/m,
  /cargo\s+(install|update|uninstall)\s+/m,
  /gem\s+install\s+/m,
  /brew\s+install\s+/m,
  /brew\s+uninstall\s+/m,
  /choco\s+install\s+/m,
  /scoop\s+install\s+/m,
  /wget\s+/m,
  /curl\s+/m,
  /cargo\s+update/m,
  /git\s+restore/m,
  /git\s+switch/m,
  /git\s+checkout\s+[^-]/m,
  /sed\s+-i/m,
  /sed\s+--in-place/m,
  /awk\s+\{[^}]*print/m,
  /xargs\s+/m,
  /find\s+[^-]\s+-exec/m,
  /find\s+[^-]\s+-delete/m,
  /parallel\s+/m,
  /timeout\s+/m,
  /nohup\s+/m,
  /disown\s+/m,
  /bg\s+/m,
  /fg\s+/m,
  /jobs\s+/m,
  /tmux\s+new-session/m,
  /screen\s+-S/m,
  /systemctl\s+(start|enable|disable)\s+/m,
  /service\s+(start|stop|restart)\s+/m,
  /update-rc\.d\s+/m,
  /chkconfig\s+/m,
  /export\s+[A-Z_]+=/m,
  /set\s+[A-Z_]+=/m,
  /alias\s+/m,
  /unalias\s+/m,
  /unset\s+/m,
  /ulimit\s+/m,
  /umask\s+/m,
  /nice\s+/m,
  /renice\s+/m,
  /ionice\s+/m,
  /chrt\s+/m,
  /taskset\s+/m,
  /prlimit\s+/m,
  /setarch\s+/m,
  /unshare\s+/m,
  /nsenter\s+/m,
  /ldconfig\s+/m,
  /ldd\s+/m,
  /objdump\s+/m,
  /readelf\s+/m,
  /nm\s+/m,
  /strace\s+/m,
  /ltrace\s+/m,
  /perf\s+/m,
  /valgrind\s+/m,
  /gdb\s+/m,
  /objcopy\s+/m,
  /strip\s+/m,
  /strings\s+/m,
  /xxd\s+/m,
  /hexdump\s+/m,
  /od\s+/m,
  /srm\s+/m,
  /shred\s+/m,
  /wipefs\s+/m,
  /blkdiscard\s+/m,
  /fstrim\s+/m,
  /hdparm\s+/m,
  /sdparm\s+/m,
  /smartctl\s+/m,
  /badblocks\s+/m,
  /fsck\s+/m,
  /tune2fs\s+/m,
  /resize2fs\s+/m,
  /e2fsck\s+/m,
  /debugfs\s+/m,
  /dumpe2fs\s+/m,
  /lsblk\s+/m,
  /blkid\s+/m,
  /findmnt\s+/m,
  /mount\s+/m,
  /umount\s+/m,
  /swapon\s+/m,
  /swapoff\s+/m,
  /lsof\s+/m,
  /fuser\s+/m,
  /flock\s+/m,
  /inotifywait\s+/m,
  /inotifywatch\s+/m,
  /iwconfig\s+/m,
  /iwlist\s+/m,
  /iw\s+/m,
  /rfkill\s+/m,
  /bluetoothctl\s+/m,
  /hciconfig\s+/m,
  /hcitool\s+/m,
  /wpa_cli\s+/m,
  /wpa_supplicant\s+/m,
  /nmcli\s+/m,
  /nmtui\s+/m,
];

export function classifyCommand(command: string): SafetyResult {
  const trimmed = command.trim().replace(/\s+/g, ' ');

  for (const pattern of BLOCKED_PATTERNS) {
    if (pattern.test(trimmed)) {
      return {
        level: 'blocked',
        reason: `Command matches blocked pattern: ${pattern}`,
        warnings: ['This command is blocked for safety reasons'],
      };
    }
  }

  const warnings: string[] = [];

  for (const pattern of DANGEROUS_PATTERNS) {
    if (pattern.test(trimmed)) {
      warnings.push(`Command requires confirmation: matches pattern ${pattern}`);
    }
  }

  const hasShellMeta = /[;|&`$(){}[\]<>]/.test(trimmed);
  const isLong = trimmed.length > 200;

  if (warnings.length > 0) {
    return {
      level: 'dangerous',
      reason: 'Command matches dangerous patterns',
      warnings,
    };
  }

  if (hasShellMeta) {
    return {
      level: 'elevated',
      reason: 'Command contains shell metacharacters',
      warnings: ['Shell metacharacters detected; proceed with caution'],
    };
  }

  if (isLong) {
    return {
      level: 'elevated',
      reason: 'Command is unusually long',
      warnings: ['Long command detected; ensure it is correct'],
    };
  }

  return {
    level: 'normal',
    reason: 'Command appears safe',
    warnings: [],
  };
}

export function isBlocked(command: string): boolean {
  return classifyCommand(command).level === 'blocked';
}

export function getSafetyLabel(level: SafetyLevel): string {
  const labels: Record<SafetyLevel, string> = {
    blocked: '⛔ BLOCKED',
    dangerous: '⚠️  DANGEROUS',
    elevated: '⚡ ELEVATED',
    normal: '✅ NORMAL',
  };
  return labels[level];
}
