import { describe, it, expect } from 'vitest';
import { mkdtempSync, existsSync, readFileSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { BUNDLED_SKILLS } from './bundled-skills.js';
import { parseFrontmatter } from './skill-loader.js';
import { SkillManager } from './skill-manager.js';

/**
 * Regression coverage for the bundled partner skills generated by
 * scripts/sync-partner-skills.mjs.
 *
 * The important case is the frontmatter one: MyCode's parseFrontmatter does not
 * implement YAML block scalars, so an upstream `description: >` or
 * `description: |` parses to the literal ">" or "|". That is exactly what the
 * model sees in the skill index, so a silently-wrong description means the
 * skill is never selected. These tests pin the generated frontmatter to
 * single-line descriptions that survive the real parser.
 */

const NAMES = ['ponytail', 'humanizer', 'strategic-compact'] as const;

const bundled = (n: string) => {
  const b = BUNDLED_SKILLS.find(s => s.name === n);
  if (!b) throw new Error(`bundled skill not found: ${n}`);
  return b;
};

describe('partner skills', () => {
  it('are bundled with SKILL.md, the verbatim upstream file, and a NOTICE', () => {
    for (const n of NAMES) {
      expect(Object.keys(bundled(n).files).sort()).toEqual(['NOTICE', 'SKILL.md', 'UPSTREAM-SKILL.md']);
    }
  });

  it('carry attribution naming the upstream repo and licence', () => {
    const expected: Record<string, string> = {
      ponytail: 'DietrichGebert/ponytail',
      humanizer: 'blader/humanizer',
      'strategic-compact': 'affaan-m/ECC',
    };
    for (const n of NAMES) {
      const notice = bundled(n).files['NOTICE'];
      expect(notice).toContain(expected[n]);
      expect(notice).toContain('MIT');
    }
  });

  it('parse to real descriptions through the real frontmatter parser', () => {
    for (const n of NAMES) {
      const fm = parseFrontmatter(bundled(n).files['SKILL.md']);
      expect(fm.name).toBe(n);
      expect(fm.description).toBeTruthy();
      // A block scalar would collapse to the indicator character.
      expect(fm.description).not.toBe('>');
      expect(fm.description).not.toBe('|');
      expect(fm.description!.length).toBeGreaterThan(60);
      expect(fm.tags!.length).toBeGreaterThan(0);
    }
  });

  it('seed into the skills dir and surface in the prompt index', () => {
    const home = mkdtempSync(join(tmpdir(), 'mycode-home-'));
    const mgr = new SkillManager({ homeDir: home });
    const seeded = mgr.seedBundledSkills();
    for (const n of NAMES) expect(seeded).toContain(n);

    for (const n of NAMES) {
      for (const f of ['SKILL.md', 'UPSTREAM-SKILL.md', 'NOTICE']) {
        expect(existsSync(join(home, 'skills', n, f)), `${n}/${f}`).toBe(true);
      }
    }

    const indexed = mgr.index().filter(e => (NAMES as readonly string[]).includes(e.name));
    expect(indexed.length).toBe(NAMES.length);
    for (const e of indexed) expect(e.description.length).toBeGreaterThan(60);
  });

  it('re-seeding is idempotent and never clobbers user edits', () => {
    const home = mkdtempSync(join(tmpdir(), 'mycode-home2-'));
    const mgr = new SkillManager({ homeDir: home });
    mgr.seedBundledSkills();
    expect(mgr.seedBundledSkills()).toEqual([]);

    const p = join(home, 'skills', 'ponytail', 'SKILL.md');
    writeFileSync(p, readFileSync(p, 'utf-8') + '\nMY OWN EDIT\n', 'utf-8');
    mgr.seedBundledSkills();
    expect(readFileSync(p, 'utf-8')).toContain('MY OWN EDIT');
  });

  it('adapt strategic-compact to MyCode and keep the upstream file untouched', () => {
    const { files } = bundled('strategic-compact');
    // MyCode surfaces /compress (alias /compact) + the compressThreshold auto-compress.
    expect(files['SKILL.md']).toContain('/compress');
    expect(files['SKILL.md']).toContain('compressThreshold');
    // The Claude Code hook and its env vars do not exist here.
    expect(files['SKILL.md']).not.toContain('suggest-compact.js');
    expect(files['SKILL.md']).not.toContain('~/.claude/settings.json');
    expect(files['SKILL.md']).not.toContain('CLAUDE_CODE_AUTO_COMPACT_WINDOW');
    // Upstream is preserved verbatim for attribution and diffing.
    expect(files['UPSTREAM-SKILL.md']).toContain('suggest-compact.js');
  });

  it('keep self-contained bodies for ponytail and humanizer', () => {
    // Neither should depend on an external binary or another harness's config.
    for (const n of ['ponytail', 'humanizer'] as const) {
      const md = bundled(n).files['SKILL.md'];
      expect(md).not.toContain('npm install -g');
      expect(md).not.toContain('~/.claude/');
    }
    // Spot-check that the substantive upstream content survived the sync.
    expect(bundled('ponytail').files['SKILL.md']).toContain('## The ladder');
    expect(bundled('humanizer').files['SKILL.md']).toMatch(/not-X-but-Y/i);
  });
});
